export const skillsData = [
  "HTML",
  "CSS",
  "Tailwind CSS",
  "Bootstrap",
  "ReactBootstrap",
  "Next JS",
  "React JS",
  "Typescript",
  "Javascript",
  "Zustand",
  "Pinia",
  "Redux",
  "Framer Motion",
  "Git and Github",
  "Maptiler",
  "Leaflet",
  "Vuetify",
  "Nuxt JS",
  "Vue JS",
];
